#!/usr/bin/env bash
#
# Symlinks all the files, so you can git pull this repo and it updates

# Author: Ryan A
# Date: November 02, 2025
# License: MIT

set -euo pipefail

defaults() {
	echo defaults "$@"
	command defaults "$@"
}

# Verbose ln (Thanks Dave Eddy!)
symlink() {
	printf '%55s -> %s\n' "${1/#$HOME/\~}" "${2/#$HOME/\~}"
	ln -nsf "$@"
}

symlink_folder() {
	printf '%55s -> %s\n' "${1/#$HOME/\~}" "${2/#$HOME/\~}"
	ln -sf "$@"
}

handle_folder() {
	folder="$1"
	for file in $folder/*; do
		[ -f "$file" ] || continue  # skip if not a regular file

		filename=$(basename $file)
		# Check if file exists and is not a symlink. If it is, delete it
		[[ -d ~/.$filename && ! -L ~/.$filename ]] && rm -r ~/."$filename"

		symlink "$PWD/$folder/$filename" ~/."$filename"
	done
}

git submodule init
git submodule update

dotfile_folders=(
	bash
	git
	tmux
	vim
	curl
	wget
	misc
	htop
	extra_bins
)

for folder in "${dotfile_folders[@]}"; do
	case "$folder" in
		extra_bins)
			[[ -d ~/$folder ]] && rm -rf ~/"$folder"
			symlink_folder "$PWD/$folder" ~/"$folder"
			;;
		vim)
			[[ -d ~/.vim && ! -L ~/.vim ]] && rm -r ~/.vim

			symlink "$PWD/vim/vim_folder" ~/.vim
			handle_folder "vim"
			;;
		*)
			handle_folder "$folder"
			;;
	esac
done

if [[ -t 1 ]]; then
	vim '+PlugInstall --sync' +qa
else
	printf "may need to run:\n\tvim +'PlugInstall --sync' +qa\n"
fi

echo
echo "$(echo $LESS_TERMCAP_us)DOTFILES INSTALLED SUCCESSFULLY. CAN TEST EXTRA BINS WITH 'ryan_test'"
