#!/usr/bin/env bash

ask_permission() {
    local prompt="$1"
    local ans

    read -r -p "$prompt (Y/n) [default: Y]: " ans
    ans=${ans:-y}  # default to yes if empty

    [[ "$ans" =~ ^[Yy]$ ]]
}

# UV - Great in python
ask_permission "Install UV?" && curl -LsSf https://astral.sh/uv/install.sh | sh
